name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar el flujo de trabajo manualmente

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Establece un tiempo máximo para evitar ejecuciones bloqueadas

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obtiene todo el historial para etiquetas y versiones

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle  # Habilita el caché de dependencias de Gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle Build
        run: ./gradlew autoBuild
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7
