name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Native Code
      run: ./gradlew externalNativeBuild
    
    - name: Upload Native Libraries
      uses: actions/upload-artifact@v3
      with:
        name: native-libs
        path: app/build/intermediates/cmake/debug/obj/
